### ISSUE TITLE
As I said on Twitter

### ISSUE THREAD

**Issue by jameshunterbr** [Chris-Engelhardt/data_sci_guide#3]
I'll be pleased to help, especially on Bioinformatics issues. I'll start off with this link to an excellent course by Prof. Kristin Sainani of Stamford:
https://lagunita.stanford.edu/courses/Medicine/MedStats./Summer2015/about

The course covers in a clear way many key issues regarding inference using R.

**Comment by Chris-Engelhardt** [comment]
Thank you for your help! Do you want me to add you to our Slack channel? If so, please DM to me your email.

**Comment by jameshunterbr** [comment]
I'd like that. Email: jameshunterbr@gmail.com

James R. Hunter
jameshunterbr@gmail.com (mailto:jameshunterbr@gmail.com)
55-11-95327-5656 (tel:55-11-95327-5656)
Laboratório de Retrovirologia, EPM, UNIFESP (https://maps.google.com/?q=Laborat%C3%B3rio%20de%20Retrovirologia%2C%20EPM%2C%20UNIFESP)

**Comment by Chris-Engelhardt** [comment]
@jameshunterbr you should have received an invite to the Slack channel via email. Can you please confirm?

**Comment by jameshunterbr** [comment]
I’ve entered the channel, Chris.

Jim

**Comment by Chris-Engelhardt** [comment]
Awesome!
